version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.14
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-227-251-33.compute-1.amazonaws.com
            port: '5432'
            database: decf3ipah77fp4
            ssl: true
            user: jvhdzaojoebcwk
            password: f42d8138e7bdae9b4dc4e7fb73f4a511c67568f85d4bf771a192216f42fcc183
            migrations: true